INSERT ALL
INTO SALESMAN VALUES (5001,'James Hoog', 'New York' , 15)
INTO SALESMAN VALUES (5002,'Nail Knite', 'Paris' , 13)
INTO SALESMAN VALUES (5005,'Pit Alex', 'London' , 11)
INTO SALESMAN VALUES (5006,'McLyon', 'Prema' , 14)
INTO SALESMAN VALUES (5007,'Paul Adam', 'Rome' , 13)
INTO SALESMAN VALUES (5003,'Lauson Hen', 'San Jose' , 12)
SELECT 1 FROM DUAL;
SELECT * FROM SALESMAN;
